### ISSUE TITLE
[fix] 기타 자질구래 수정 (스타일 등)

### ISSUE THREAD

**Issue by iam-hyo** [Face-Pizza/Cheese-4cut_by-facePizza#19]
## ✔️ Issue
스타일 등 지속적으로 수정해야하는 일들 리스트입니다. 
혹시 보시는분들중 추가하고싶은게 있다면 댓글로 달아주세요

## 📝 To-do

- [ ] 프레임 안짤리게 간격 수정
- [ ] 메인화면 <표정챌린지> 일러스트 수정
- [ ] SelcetPage 셀렉트바 수정
- [ ] 사진 프린트 네장까지

- [ ] 카메라로 찍었을 떄 사진 너비가 안짤리도록 수정

- [ ] 홈화면 지내표 일러스트 수정
- [ ] 네컷만화 쪽 번호 표시

## 🛠비고 
QRcode 페이지 고도화 및 instagram 계정 연결
