### ISSUE TITLE
[refactor] SelectPage 사진 구현 방식 Canvas API 로 변경하기

### ISSUE THREAD

**Issue by iam-hyo** [Face-Pizza/Cheese-4cut_by-facePizza#3]
## ✔️ Issue
현재 구현 방식은 그냥 z-index사용해서 얹어서 html에 렌더링 하는 방식.
현재 방식으로는 html을 캡쳐해야 완성된 이미지를 얻을 수 있는 문제가 있어서 화질이 떨어짐.
따라서 다음의 개요에 따라 수정

1. Canvas 요소 생성:
<canvas> 태그를 사용하거나 JavaScript에서 동적으로 생성합니다. 이 캔버스는 그림을 그릴 공간입니다.
canvas.getContext('2d') 메서드를 사용해 2D 렌더링 컨텍스트를 얻습니다.

2. 이미지 및 프레임 로드:
Image 객체를 사용하여 사진과 프레임 이미지를 비동기로 로드합니다.
image.onload 이벤트를 통해 이미지가 로드되면, 캔버스에 그리기 작업을 수행할 수 있습니다.

3.이미지를 캔버스에 그리기:
context.drawImage() 메서드를 사용해 사진 및 프레임 이미지를 원하는 좌표에 그립니다.
원하는 레이아웃(예: 네 컷 사진)을 맞추기 위해 좌표와 크기를 조정합니다.

4.QR 코드 추가:
QR 코드 이미지도 Image 객체로 로드하고, 캔버스에 그립니다.
원하는 위치에 QR 코드를 배치하여 추가합니다.

5. 이미지 데이터 저장:
canvas.toDataURL() 또는 canvas.toBlob() 메서드를 사용해 최종 이미지를 PNG, JPEG 등의 포맷으로 저장합니다.
이 방법을 통해 QR 없는 버전과 QR 있는 버전을 각각 캡처하여 저장할 수 있습니다.

## 📝 To-do

- [x] Canvas 설정하고 사진 만드는 방법 다시 구현
- [x] 캡처해서 PrintPage에서 보이게 설정
- [x] 더미 Qr 설정해서 넣었다 뻈다 테스트
- [x] #8

## 🛠 Working time

이번 주말간
21, 22 양일간 완료하는게 목표
